Fix hangup in make package on a non-configured port
When you repeatedly cancelled `make config` dialog, `make package`
called it, but it was hidden. As a result, portmaster hanged. Fix
it by disabling `make config` (if you've not configured it so far,
you really don't want to do it now).

diff --git a/portmaster b/portmaster
--- a/portmaster
+++ b/portmaster
@@ -4185,7 +4185,7 @@ fi
 if [ -n "$MAKE_PACKAGE" ]; then
 	if [ -z "$use_package" ]; then
 		echo "===>>> Creating a package for new version $new_port"
-		pm_make_s package >/dev/null || fail "Package creation of $new_port failed"
+		pm_make_s -D_OPTIONS_OK package >/dev/null || fail "Package creation of $new_port failed"
 		echo "	===>>> Package saved to $PACKAGES/All" ; echo ''
 	else
 		pm_pkg_create $PACKAGES $new_port
